---
title: "Inheritance and R expressions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Inheritance and R expressions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{html, child="fragments/codeblock.html", echo=FALSE}
```

## Defaults and inheritance

The `default` configuration provides a set of values to use when no named configuration is active. Other configurations automatically inherit all `default` values so need only define values specialized for that configuration.

For example, in this configuration the `production` configuration doesn't specify a value for `trials` so it will be read from the `default` configuration:

<p class = "codeblock-label">config.yml</p>

```yaml
default:
  trials: 5
  dataset: "data-sampled.csv"
  
production:
  dataset: "data.csv"
```

All configurations automatically inherit from the "default" configuration. Configurations can also inherit from one or more other named configurations. For example, in this file the `production` configuration inherits from the `test` configuration:

<p class = "codeblock-label">config.yml</p>

```yaml
default:
  trials: 5
  dataset: "data-sampled.csv"

test:
  trials: 30
  dataset: "data-test.csv"
  
production:
  inherits: test
  dataset: "data.csv"
```

## Embedding R code inside the yaml file

You can execute R code within configuration files by prefacing values with `!expr`. This could be useful in the case where you want to base configuration values on environment variables, R options, or even other config files. For example:

<p class = "codeblock-label">config.yml</p>

```yaml
default:
  cores: 2
  debug: true
  server: "localhost:5555"
   
production:
  cores: !expr getOption("mc.cores")
  debug: !expr Sys.getenv("ENABLE_DEBUG") == "1"
  server: !expr config::get("server", file = "/etc/server-config.yml")
```

### Referencing previously assigned parameters

You can use any previously assigned parameter inside of R code so long as it is assigned directly.

<p class = "codeblock-label">config.yml</p>

```yaml
default:
  file: "data.csv"

test:
  data_dir: "test/out"
  dataset: !expr file.path(data_dir, file)
  
production:
  data_dir: "production/out"
  dataset: !expr file.path(data_dir, file)
```

You can't reference other expressions, but it will only generate a warning and then assign a NULL value.
