---
title: "Using config with Posit Connect"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using config with Posit Connect}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{html, child="fragments/codeblock.html", echo=FALSE}
```

The purpose of the `config` package is to respond to environment variables that could be set to different values on different machines. Specifically, config reacts to the value of `R_CONFIG_ACTIVE`, and this allows you to set configurations for different machines, e.g. in dev or production.

If you deploy your code to a Posit Connect instance, then you can use the fact that Connect sets the value of `R_CONFIG_ACTIVE` to `rsconnect`.

This means you can create a configuration file using the value `rsconnect`, for example:


<p class = "codeblock-label">config.yml</p>

``` yaml
default:
  trials: 5
  dataset: "data-sampled.csv"
  
rsconnect:
  trials: 30
  dataset: "data.csv"
```

Note: this value can be configured by your system administrator, so check your own system configuration!  See <https://docs.posit.co/connect/admin/appendix/configuration/#R.ConfigActive> for detail.

## Using config for staging and prod

You may have the use case that you use the same Connect instance to host two instances of your app, for staging (test) and production.

In this use case you will soon run into the problem that an individual user can not change the the environment variable `R_CONFIG_ACTIVE`, since this is configured system-wide by the administrator.

But you can still use `config` to set different values for staging and prod, by changing the environment variable that `config::get()` looks at.


Specifically, you must specify a different `config` argument to `config::get()`.  For example, you can create a new environment variable for your Connect app, called `R_CONFIG_ACTIVE_APP`, and then use `config::get()` like this:

``` R
config::get("trials", config = Sys.getenv("R_CONFIG_ACTIVE_APP"))
```

Additionally, you may want to utilize the inheritance of `config` yaml files, by having a common configuration for `connect` and then staging and prod configurations that inherit from the `connect` configuration.

In such a case, you may have a `config.yml` file like this:


<p class = "codeblock-label">config.yml</p>

``` yaml
default:
  trials: 5
  dataset: "data-sampled.csv"

connect:
  trials: 30
  
staging:
  inherits: connect
  dataset: "data-staging.csv"
  
prod:
  inherits: connect
  dataset: "data.csv"
```


If you configure the environment variable correctly, you should get the appropriate `dataset` values for staging (`data-staging.csv`) and prod (`data.csv`).
